name: Deploy to Server (SvelteKit - dynamic with PM2 config)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Upload & Deploy
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -tt -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            set -e

            # Zielverzeichnis erstellen & betreten
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}

            # Repo klonen oder updaten
            if [ -d ".git" ]; then
              git pull origin master
            else
              find . -mindepth 1 -delete
              git clone https://github.com/CrayonGamerHD-Philipp/edelweisspiraten-website.git .
            fi

            # In den Web-Ordner wechseln
            cd web

            # Abhängigkeiten installieren & Build ausführen
            npm install
            npm run build

            # PM2-Prozess neu starten mit ecosystem.config.js
            pm2 delete sveltekit || true
            pm2 start ecosystem.config.js
            pm2 save
          EOF