name: Deploy to Server (SvelteKit)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Upload & Deploy
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -tt -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}

            if [ -d ".git" ]; then
              git pull origin master
            else
              find . -mindepth 1 -delete
              git clone https://github.com/CrayonGamerHD-Philipp/edelweisspiraten-website.git .
            fi

            cd web

            npm install

            if npm run build; then
              pm2 restart sveltekit || pm2 start npm --name sveltekit -- start
              pm2 save
            else
              echo "Build failed – skipping PM2 start"
              exit 1
            fi
          EOF
        
